---
classes:
  - prometheus::server
  - ruby
ruby::gems_version: latest
prometheus::server::version: 2.19.0
prometheus::scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: '10s'
    scrape_timeout: '10s'
    static_configs:
      - targets:
          - 'localhost:9090'
        labels:
          alias: 'Prometheus'
  - job_name: 'netdata-scrape'
    scrape_interval: '5s'
    scrape_timeout: '5s'
    static_configs:
      - targets:
          - 'district-delta.core.ghostlink.net:19999'
          - 'valkyrie.core.ghostlink.net:19999'
        labels:
          alias: 'netdata-scrape'
    metrics_path: '/api/v1/allmetrics?format=prometheus'